### PR TITLE
Add default shader permutation for srgb conversion

### PR DESCRIPTION
**Pull request by cwfitzgerald**
It is common for people to eventually write to a converting framebuffer (`Bgra8UnormSrgb`) and need shaders to output in linear color. This adds shader permutations for outputting in both linear and srgb. I have added separate functions so that the linker can remove the unused shader.

### CODE REVIEW

**Comment by Yatekii** [comment]
> It is common for people to eventually write to a converting framebuffer (`Bgra8UnormSrgb`) and need shaders to output in linear color. This adds shader permutations for outputting in both linear and srgb. I have added separate functions so that the linker can remove the unused shader.

I have no clue about this, but sounds fair to me.



> I think we should release after this PR, but we'd need a minor version bump

I did a release yesterday. But tbh I am not sure I am ok with the builder patterns. I think raw structs would be a better fit ...

**Comment by cwfitzgerald** [comment]
> I did a release yesterday. But tbh I am not sure I am ok with the builder patterns. I think raw structs would be a better fit ...

We found very similar for wgpu itself, up to you on what you want to do, it seems reasonable to wait until a decision has been made wrt builders

**Comment by Yatekii** [comment]
I think we should remove them to be honest. I didn't like them much initially but I also didn't wanna nag after all the work he did. And the impl itself was fine :) So maybe we should remove them. Because I think builders are only worth it if they actually configure stuff internally or similar (they can be worth it to compile an entire SVG tree down to a single mov xd (I did that :P))

**Comment by cwfitzgerald** [comment]
That's fine with me, I haven't actually used the latest api, but going with the Descriptor pattern like wgpu seems a tried and true way to allow for complex init when you just have a pile of options.

**Pull request merged**
