### PR TITLE
fix examples to use new winit

### PR DESCRIPTION
**Pull request by aentity**
i'm sorry, forgot update winit in examples; i tested with another project it works fine :)

i also accidentally rust formated examples (format on save); i can undo if want but can i just leave it?

### CODE REVIEW

**Comment by Yatekii** [comment]
Thanks for fixing it! Somehow GH actions don't trigger for PRs? Weird ... I need to fix this.

cargo fmt is ok for me. I was strongly against it previously but since most people are unable to format code properly it's basically a requirement :)

**Comment by aentity** [comment]
Cool, is it ok to have new crates now?:)

**Comment by Yatekii** [comment]
Damn, yes, ofc, I simply forgot :/

**Comment by aentity** [comment]
@Yatekii ping for new crate? :)

**Comment by Yatekii** [comment]
Hey @aentity I am really sorry :/ Very unreliable on my end ... I just published it. I hope everything is fine. If you are on Matrix or IRC (Yatekii on both) we can maybe have a quick talk too, I could make you a maintainer; because it is really not ok that I am so lazy and you folks gotta suffer from it ...

**Comment by aentity** [comment]
its ok don't feel bad, just pinged so you didn't forget :)))

**Pull request merged**
