### PR TITLE
update to latest wgpu-rs api

### PR DESCRIPTION
**Pull request by aentity**
* update wgpu api
* update winit and raw-window-handle deps

### CODE REVIEW

**Comment by aentity** [comment]
ping @Yatekii can merge think

**Comment by Yatekii** [comment]
How did I miss this again ...

**Comment by Yatekii** [comment]
LGTM! Thanks a lot for this :)

**Comment by Yatekii** [comment]
@aentity How did you update to v0.4.0 when it was only released today? Did you just do that preliminary?

**Comment by aentity** [comment]
@Yatekii yes, i updated 4 day ago, then when released, just use crates

**Pull request merged**
