### PR TITLE
Remove simple API

### PR DESCRIPTION
**Pull request by cwfitzgerald**
## Checklist

- [x] `cargo clippy` reports no issues
- [x] `cargo doc` reports no issues
- [x] [`cargo deny`](https://github.com/EmbarkStudios/cargo-deny/) issues have been fixed or added to `deny.toml`
- [x] human-readable change descriptions added to the changelog under the "Unreleased" heading.
  - [x] If the change does not affect the user (or is a process change), preface the change with "Internal:"
  - [x] Add credit to yourself for each change: `Added new functionality @githubname`.

## Description

We haven't published this in a couple releases, I don't want  to maintain this, let's nix this.

### CODE REVIEW

**Comment by benmkw** [comment]
Was there a larger inconvenience? Looking at the history it seems https://github.com/Yatekii/imgui-wgpu-rs/commits/c7ae1fb897cdd31e0b0c86717a603ab253ac8624/simple-api and https://github.com/Yatekii/imgui-wgpu-rs/commits/a153c00d81db7812a1b4621ad9a0e8fd34a17610/src/simple_api.rs were relatively mechanical changes. Would it thus make sense to release it instead of removing it?

On the other hand I recognise nobody is probably using it at this point which is also a chicken egg problem because its not released I guess.

IMO it's a useful API to have but if its too much maintenance cost its your choice of course.

**Comment by Yatekii** [comment]
I was in the belief that we agreed to remove this because it was not actually much used by most. But I might have been too much out of the loop here :/

**Comment by cwfitzgerald** [comment]
@benmkw Basically it's a very large increase in scope from the purpose of this lib. I agree it is likely useful but someone is going to need to step up to maintain it as part of its own project, and I don't want us to be burdened by it.

**Comment by benmkw** [comment]
All right I set up a git repo of the code https://github.com/benmkw/imgui-wgpu-simple-api and will update it on demand.

**Pull request merged**
