### PR TITLE
Update WGPU to 0.5

### PR DESCRIPTION
**Pull request by aloucks**
- Update WGPU to 0.5
- Remove Cargo.lock
- Run cargo fmt
- Make glsl-to-spirv optional (and update github workflows)
- Bump version to 0.6.0

### CODE REVIEW

**Comment by Yatekii** [comment]
Well, now we have two PRs ^^ guess it's a tough descision :D

**Comment by aloucks** [comment]
I've done most of the 0.5 changes in the previous PRs and applied the other discussed changes from https://github.com/Yatekii/imgui-wgpu-rs/pull/10. (rustfmt and Cargo.lock removal). I made certain to not make any changes in the commit that re-formats the project as I think this makes review and history very murky.

I've also made glsl-to-spriv and optional dep that is really only ever needed for development of this crate.

**Comment by Yatekii** [comment]
Hey, could you also change the README to the used versions?

**Comment by aloucks** [comment]
@Yatekii done.

**Pull request merged**
